;------------------------------------------------------------------------------;
;                                                                              ;
;              Library for loading and starting kernel mode driver:            ;
;                     connect include files with subroutines.                  ;
;                                                                              ;
;------------------------------------------------------------------------------;

include 'load_kmd.inc'