;------------------------------------------------------------------------------;
;                                                                              ;
; System Information Library: constants and variables with pre-defined values. ; 
;                                                                              ;
;------------------------------------------------------------------------------;

; TODO.
; Table for system information handlers sequentally call.

