;------------------------------------------------------------------------------;
;                                                                              ;
;                 Library for loading and interpreting inf file:               ;
;                constants and variables with pre-defined values.              ;
;                                                                              ;
;------------------------------------------------------------------------------;

align 8
CONFIG_VALUES CONFIGVALUES (0) 