;------------------------------------------------------------------------------;
;                                                                              ;
;              Library for loading and starting kernel mode driver:            ;
;                constants and variables with pre-defined values.              ;
;                                                                              ;
;------------------------------------------------------------------------------;

; Reserved.